### ISSUE TITLE
Widget not hiding when invoking array funktion

### ISSUE THREAD

**Issue by Leevy27** [jayanam/fast-carve#39]
Hi Jayanam,

I noticed today, that adding an array with the fastcarve tool, the widget to change the parameters in X,Y,Z is appearing and working, but when I apply the array modifier they are not hiding. When I then switch from Modeling Tab to Layout Tab i get the following error:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\BLENDER-Leevy\2.80\scripts\addons\fast-carve-fast-carve-2-8\widgets\bl_ui_draw_op.py", line 60, in modal
    if self.handle_widget_events(event):
  File "C:\Program Files\Blender Foundation\BLENDER-Leevy\2.80\scripts\addons\fast-carve-fast-carve-2-8\widgets\bl_ui_draw_op.py", line 52, in handle_widget_events
    if widget.handle_event(event):
  File "C:\Program Files\Blender Foundation\BLENDER-Leevy\2.80\scripts\addons\fast-carve-fast-carve-2-8\widgets\bl_ui_widget.py", line 93, in handle_event
    inrect = self.is_in_rect(x, y)
  File "C:\Program Files\Blender Foundation\BLENDER-Leevy\2.80\scripts\addons\fast-carve-fast-carve-2-8\widgets\bl_ui_widget.py", line 113, in is_in_rect
    area_height = self.get_area_height()
  File "C:\Program Files\Blender Foundation\BLENDER-Leevy\2.80\scripts\addons\fast-carve-fast-carve-2-8\widgets\bl_ui_widget.py", line 110, in get_area_height
    return self.context.area.height    
AttributeError: 'NoneType' object has no attribute 'height'

location: <unknown location>:-1

Working on Blender 2.8 official release but portable version on a Windows 10 PC.

**Comment by jayanam** [comment]
Ok thx, will have a look
